// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace ZorbaGameplayTags
{
	ZORBA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Attack_Primary);
	ZORBA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Attack_Heavy);
	ZORBA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Defend);
	ZORBA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Dodge);

	ZORBA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attacking);
	ZORBA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Defending);
	ZORBA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ParryWindow);
	ZORBA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_HitReact);
	ZORBA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_StaminaDepleted);
	ZORBA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Exhausted);
	ZORBA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enraged);
	ZORBA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stunned);
	ZORBA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	ZORBA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Invulnerable);

	ZORBA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Melee_TraceBegin);
	ZORBA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Melee_TraceEnd);
	ZORBA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combo_WindowBegin);
	ZORBA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combo_WindowEnd);
}
